### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by tomerarnon** [spacecraft-design-lab-2019/groundtruth-simulator#39]
We've talked about validating stuff before, but here it is as an issue.  I've started an example test file in [Simulator/Test/test_matrix_math.py](https://github.com/spacecraft-design-lab-2019/groundtruth-simulator/blob/master/Simulator/Test/test_matrix_math.py). Anyone can expand on that and create their own, etc.. You can run the tests by running `pytest` from the command prompt in the root directory of the project. Although I didn't do it there, whenever relevant, these tests should also test edge cases/failure conditions. Note that the filename has the form `"test_....py"`. This is how pytest knows to recognize it as a test file.

Also, @ethanleboeuf @pdetrempe have a lot of experience writing these kinds of tests and are happy to be a resource (I asked 😄)

**Comment by hridujain** [comment]
Validation of the sim is in progress. However, closing this issue as we don't need this here.
